services:
  timescaledb:
    image: timescale/timescaledb:latest-pg16
    container_name: vigil-timescaledb
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: vigil
    ports:
      - "5435:5432"
    volumes:
      - timescale_data:/var/lib/postgresql/data
      - ./sql:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    shm_size: 256mb

volumes:
  timescale_data:
